### ISSUE TITLE
Background play not working 

### ISSUE THREAD

**Issue by Pravesh471** [ReVanced-Extended-Community/Community-Guides#11]
Hi , whenever I switch from YouTube to another app then after 1 minute the background play stops and the video goes into infinite buffer , i am using the latest version of revanced manager please help me with this issue

**Comment by KobeW50** [comment]
Hi there. This repository is only for guides.

For support, please ask in the [subreddit](https://www.reddit.com/r/revancedextended/) or [Telegram group](https://t.me/revanced_extended_chat/).
