### ISSUE TITLE
Buffering 

### ISSUE THREAD

**Issue by Gariibi** [ReVanced-Extended-Community/Community-Guides#12]
From the morning of 3 may 2024 YouTube revancned is not working only some videos are playing and others are just buffering

**Comment by Reconzero** [comment]
You solve it?

**Comment by Gariibi** [comment]
No issues is not resolved till now are you also facing the same issue

**Comment by petandk** [comment]
YouTube is fighting against adblockers by somehow increasing buffering times and other nasty things, so I guess we'll have to wait until someone finds out a way to... Bypass it. They're so strict, even people paying real YouTube premium are facing buffering problems.

**Comment by KobeW50** [comment]
I apologize that the troubleshooting guides were not updated with information to resolve this. It will be updated in the coming days. For now, refer to https://github.com/inotia00/ReVanced_Extended/issues/1954

ReVanced released a fix for this today, so it is likely this fix will be released by inotia00 (the ReVanced Extended developer) in the coming days.
