### ISSUE TITLE
YouTube Revanced crashes 

### ISSUE THREAD

**Issue by Ayush4813** [ReVanced-Extended-Community/Community-Guides#14]
While using Revanced YouTube after some time it crashes and when ever I am trying to play background music it also crashes automatically imdiately

**Comment by KobeW50** [comment]
Hi there. This repository is only for guides.

For support, please ask in the [subreddit](https://www.reddit.com/r/revancedextended/) or [Telegram group](https://t.me/revanced_extended_chat/).
