### ISSUE TITLE
Problem with revanced being rendered unusable.

### ISSUE THREAD

**Issue by Sixtechsupport** [ReVanced-Extended-Community/Community-Guides#20]
So for the pest two days. I've been having a problem with the latest version of revanced that I'm getting from the revanced manager. And It's making revanced unusable. The error is that whenever I download it. It works for like a few hours before it gives me errors like these. 

Yesterday the one I received was the "couldn't load videos," error which also didn't help. So I just wanted to mention this in case I'm not the only one with this problem currently.

![Screenshot_20240813-073009](https://github.com/user-attachments/assets/08c67780-3ffe-45e9-a41a-77d861a1cbac)

**Comment by Sixtechsupport** [comment]
Do note that when I tried to sign in all I got for account icons were icons with the letter E on them for account icons and they did nothing to help with the problem. Which wasn't great to say the least.

**Comment by KobeW50** [comment]
Hey. Btw on Discord i meant that you should move to one of the support channels in the discord server. Sorry for the misunderstanding.
Anyway, the solution be at the top of this page

https://github.com/ReVanced-Extended-Community/Community-Guides/blob/main/community-wiki/yt-troubleshooting.md#1-no-internet-connection--home-page-not-loading--account-sign-in-issues
