### ISSUE TITLE
Disabling Canada version

### ISSUE THREAD

**Issue by Ice-Hawky** [ReVanced-Extended-Community/Community-Guides#7]
Spoofing the version to disable the radio for Canadian users is not working.

**Comment by KobeW50** [comment]
Please make sure that you are using the latest supported version of YTM for the ReVanced Extended patches. 

Additionally, the Spoof app version toggle should be enabled, and the target version should be set to 4.27.53.

Here is a video demonstration if needed:

https://github.com/ReVanced-Extended-Community/Community-Guides/assets/84587632/2e3d54fc-9fa3-480e-b06d-72876e66b798

If it still doesn't work, please open a bug report in [this repository](https://github.com/inotia00/ReVanced_Extended)
